CREATE SCHEMA IF NOT EXISTS notification_service;

ALTER DEFAULT PRIVILEGES IN SCHEMA notification_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA notification_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;
